web:
  build: .
  ports:
    - "8000:8000"
  links:
    - mysql:mysql
    - redis:redis
  env_file: .env
  command: /code/manage.py runserver 0.0.0.0:8000

mysql:
  image: daocloud.io/mysql:latest
  environment:
    - MYSQL_DATABASE=django
    - MYSQL_ROOT_PASSWORD=mysql
  ports:
    - "3306:3306"

redis:
  image: daocloud.io/redis:latest
  ports:
    - "6379:6379"

